server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:test;mode=mysql
    driverClassName: org.h2.Driver
    username: test
    password: test
    initialization-mode: always
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PTL}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: ${MAIL_PTL}
        smtp:
          starttls:
            enable: ${MAIL_PTL_EBLE}
            required: ${MAIL_PTL_EBLE}
          auth: ${MAIL_PTL_EBLE}
          connectiontimeout: ${MAIL_CNT_TMOUT}
          timeout: ${MAIL_CNT_TMOUT}
          writetimeout: ${MAIL_CNT_TMOUT}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true

app:
  auth:
    jwtSecret: "Seeeeeeecccrreeeeeeetttttsss"
    jwtExpirationMsec: 864000000
  support:
    email: xxxxxxxxxx