server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:${DB_PLATFORM_PROD}://${DB_HOST_PROD:localhost}:${DB_PORT_PROD:3306}/${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    initialization-mode: always
    platform: ${DB_PLATFORM_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PTL}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: ${MAIL_PTL}
        smtp:
          starttls:
            enable: ${MAIL_PTL_EBLE}
            required: ${MAIL_PTL_EBLE}
          auth: ${MAIL_PTL_EBLE}
          connectiontimeout: ${MAIL_CNT_TMOUT}
          timeout: ${MAIL_CNT_TMOUT}
          writetimeout: ${MAIL_CNT_TMOUT}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ${JPA_DB_PLTFRM_PROD}
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: false
      path: ${DB_H2_PATH}

  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true

app:
  auth:
    jwtSecret: ${APP_JWT_SCRTS_PROD}
    jwtExpirationMsec: ${APP_JWT_EXP_MS}
  support:
    email: ${APP_SUP_MAIL}
  h2:
    path: ${DB_H2_PATH}