server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:${DB_PLATFORM_DEV}://${DB_HOST_DEV:localhost}:${DB_PORT_DEV:3306}/${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    initialization-mode: always
    platform: ${DB_PLATFORM_DEV}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: ${JPA_DB_PLTFRM_DEV}
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: ${DB_H2_PATH}

  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true

app:
  auth:
    jwtSecret: ${APP_JWT_SCRTS}
    jwtExpirationMsec: ${APP_JWT_EXP_MS}
  support:
    email: ${APP_SUP_MAIL}
  h2:
    path: ${DB_H2_PATH}
