name: Test Maven Projects
on:
  push:
    branches:
      - 'develop'

jobs:
  test: 
    runs-on: ubuntu-latest
    name: Test Maven Project
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven archetype
      id: cache-maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jdk-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: test project 
      run: mvn clean verify

  test-integration: 
    runs-on: ubuntu-latest
    needs: test
    name: Test integration Project
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven archetype
      id: cache-maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jdk-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify -Pintegration-test
